---
- hosts: all
  become: true
  tasks:
    - name: actualizar apt cache
      apt: update_cache=yes

    - name: instalar net-tools
      apt:
        name: net-tools
        state: present

    - name: instalar vim
      apt:
        name: vim
        state: present

    - name: instalar apache
      apt:
        name: apache2
        state: present

    - name: Descargar e importar clave de HashiCorp
      shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Agregar el repositorio de HashiCorp a sources.list.d
      shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: Actualizar apt cache nuevamente con los nuevos repositorios
      apt: update_cache=yes

    - name: instalar consul
      apt:
        name: consul
        state: present

    - name: verificar versión de consul
      command: consul -v

    - name: instalar nodejs
      apt:
        name: nodejs
        state: present

    - name: instalar npm
      apt:
        name: npm
        state: present

    - name: instalar git
      apt:
        name: git
        state: present

    - name: Clonar repositorio de Git y navegar a la ubicación
      shell: |
        git clone https://github.com/omondragon/consulService
        cd consulService/app
      args:
        executable: /bin/bash